// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  "use strict";
  grunt.util.linefeed = "\n";
  RegExp.quote = function(string) {
    return string.replace(/[-\\^$*+?.()|[\]{}]/g, "\\$&");
  };
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    meta: {
      distPath: "dist/",
      docsAssetsPath: "docs/assets/"
    },
    clean: {
      dist: ["dist", ".tmp", "docs/dist"]
    },
    coffee: {
      dist: {
        files: [
          {
            expand: true,
            cwd: "scripts",
            src: "{,*/}{,*/}*.coffee",
            dest: ".tmp/scripts/",
            extDot: "last",
            ext: ".js"
          }
        ]
      }
    },
    requirejs: {
      dist: {
        options: {
          name: "orange",
          baseUrl: ".tmp/scripts",
          out: "<%= meta.distPath %>js/orange.js"
        }
      }
    },
    compass: {
      options: {
        sassDir: "scss",
        cssDir: "<%= meta.distPath %>css/",
        imagesDir: "images",
        relativeAssets: true
      },
      server: {
        options: {
          debugInfo: false
        }
      }
    },
    copy: {
      fonts: {
        expand: true,
        src: "fonts/*",
        dest: "<%= meta.distPath %>/"
      }
    },
    cssmin: {
      options: {
        keepSpecialComments: "*",
        noAdvanced: true,
        report: "min"
      },
      dist: {
        src: "<%= meta.distPath %>css/<%= pkg.name %>.css",
        dest: "<%= meta.distPath %>css/<%= pkg.name %>.min.css"
      }
    }
  });
  require("load-grunt-tasks")(grunt, {
    scope: "devDependencies"
  });
  require("time-grunt")(grunt);
  grunt.registerTask("dist-css", ["compass", "cssmin"]);
  grunt.registerTask("dist-js", ["coffee", "requirejs"]);
  grunt.registerTask("dist", ["clean", "dist-css", "dist-js", "copy"]);
  return grunt.registerTask("default", ["dist"]);
};
