// Generated by CoffeeScript 1.6.3
var $, gulp, path;

gulp = require('gulp');

path = require('path');

$ = require('gulp-load-plugins')();

gulp.task('clean', function() {
  return gulp.src(['./dist'], {
    read: false
  }).pipe($.clean());
});

gulp.task('css', function() {
  return gulp.src('./scss/*scss').pipe($.compass({
    project: path.join(__dirname, '/'),
    comments: false,
    css: './dist/css',
    sass: './scss'
  })).pipe(gulp.dest('dist/css')).pipe($.minifyCss()).pipe($.rename({
    extname: '.min.css'
  })).pipe(gulp.dest('./dist/css'));
});

gulp.task('scripts', function() {
  return gulp.src('./scripts/orange.coffee', {
    read: false
  }).pipe($.browserify({
    transform: ['coffeeify'],
    extensions: ['.coffee']
  })).pipe($.rename({
    extname: '.js'
  })).pipe(gulp.dest('./dist/js')).pipe($.uglify()).pipe($.rename({
    extname: '.min.js'
  })).pipe(gulp.dest('./dist/js'));
});

gulp.task('default', ['clean', 'css', 'scripts']);
