// Generated by CoffeeScript 1.6.3
'use strict';
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

require.config({
  shim: {
    'zepto': {
      exports: '$'
    },
    'orange': {
      deps: ['zepto']
    }
  },
  paths: {
    'zepto': 'http://zeptojs.com/zepto.min',
    'orange': 'https://rawgithub.com/baidao/orange/master/dist/js/orange'
  }
});

require(['zepto', 'orange'], function($, orange) {
  return $(function() {
    var html_encode;
    html_encode = function(str) {
      var s;
      s = '';
      if (str.length === 0) {
        return '';
      }
      s = str.replace(/&/g, '&gt;');
      s = s.replace(/</g, '&lt;');
      s = s.replace(/>/g, '&gt;');
      s = s.replace(/\'/g, '&#39;');
      s = s.replace(/\'/g, '&quot;');
      s = s.replace(/\n/g, '<br>');
      return s;
    };
    $('pre').each(function(index, item) {
      var source;
      source = $(item).html();
      $(item).parent('.source').siblings('.perform').html("<div class='iphone'>" + source + "</div>");
      return $(item).html(html_encode(source));
    });
    prettyPrint();
    if (__indexOf.call(window, 'ontouchend') < 0) {
      $(document).delegate('body', 'click', function(e) {
        return $(e.target).trigger('tap');
      });
    }
    $('#main_content_wrap').show();
    return $('#doc-spinner').remove();
  });
});
