// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define(['./os', './transition', './requestAnimationFrame', './segmentControl', './carousel', './counter', './spinner', './dialog'], function() {});

}).call(this);
